bt_app_test:
  ros__parameters:
    bt_tree_node_model: "/home/user/Eurobot-2025-Main-ws/src/bt_app_test/bt_config/bt_tree_node_model.xml"
    groot_xml_config_directory: "/home/user/Eurobot-2025-Main-ws/src/bt_app_test/bt_config/"