version: '3'
name: eurobot-main
services:
  main-ws:
    build:
      context: .
      args:
        USERNAME: user
    image: tedwang2/main-ws:latest
    container_name: main-ws
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    working_dir: /home/user/Eurobot-2025-Main-ws
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - ROS_WS=/home/user/Eurobot-2025-Main-ws
      - GROOT_APPIMAGE=/home/user/Eurobot-2025-Main-ws/groot/groot.AppImage
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /d/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Direct Rendering Infrastructure
      - /dev:/dev
      - ../:/home/user/Eurobot-2025-Main-ws
    ports:
      - "8765:8765"

    command: /bin/bash
