version: '3'
name: eurobot-main
services:
  main-ws:
    build:
      context: .
      args:
        USERNAME: user
    image: tedwang2/main-ws:1.1
    container_name: main-ws
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    working_dir: /home/user/Eurobot-2025-Main-ws
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - ROS_WS=/home/user/Eurobot-2025-Main-ws
      - GROOT_APPIMAGE=/home/user/Eurobot-2025-Main-ws/groot/groot.AppImage
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /d/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Direct Rendering Infrastructure
      - /dev:/dev
      - ../:/home/user/Eurobot-2025-Main-ws
    ports:
      - "8765:8765"

    command: /bin/bash
    # command: >
    #   /bin/bash -c "source /opt/ros/foxy/setup.bash 
    #   && source /home/user/Eurobot-2025-Main-ws/install/setup.bash 
    #   && ros2 launch bt_app_2025 bt_launch.py"
