/**:
  ros__parameters:
    Bot1_YellowA_config: "bt_plan_a_Yellow.xml"
    Bot1_YellowB_config: "bt_plan_b_Yellow.xml"
    Bot1_YellowC_config: "bt_plan_c_Yellow.xml"
    Bot1_BlueA_config: "bot1_blue_a.xml"
    Bot1_BlueB_config: "bot1_blue_b.xml"
    Bot1_BlueC_config: "bot1_blue_c.xml"
    Bot2_YellowA_config: "bot2_yellow_a.xml"
    Bot2_YellowB_config: "bot2_yellow_b.xml"
    Bot2_YellowC_config: "bot2_yellow_c.xml"
    Bot2_BlueA_config: "bot2_blue_a.xml"
    Bot2_BlueB_config: "bot2_blue_b.xml"
    Bot2_BlueC_config: "bot2_blue_c.xml"
    tree_node_model_config_file: "/Eurobot-2025-Main/src/bt_app_2025/bt_m_config/bt_m_tree_node_model.xml"
    groot_xml_config_directory: "/Eurobot-2025-Main/src/bt_app_2025/bt_m_config/"
