bt_app_2025:
  ros__parameters:
    # spin command : 1: front_arm 2: back_arm 3:arm_move 4:move 5: arm spin 180 6: robot spin 180
    # not_spin command : 1: front_arm 2: back_arm 3:arm_move 4:move 5: board 6: robot spin 180
    # material : 0: none 1: whole 2: 1 layer 3: 2 column 2 board 4: 2 layers
    # layer : 4: 2+1 layers

    # command, front_material, back_material
    front_collect: [1, 0, 0]
    back_collect: [2, 0, 0]

    # command, front_material, back_material, finished layer
    construct_1: [1, 3, 0, 0]

    spin_construct_2: [
      2, 0, 1, 1,
      4, 0, 0, 1,
      6, 0, 0, 1,
      4, 0, 0, 1,
      1, 0, 0, 1,
      4, 3, 0, 1,
      3, 3, 0, 1,
      5, 3, 0, 1,
      4, 3, 0, 1,
      1, 3, 0, 1,
      1, 0, 0, 1,
      4, 2, 0, 1,
      5, 2, 0, 1,
      4, 2, 0, 1,
      1, 2, 0, 1]

    spin_construct_3: [
      1, 3, 1, 0,
      4, 0, 1, 1,
      6, 0, 1, 1,
      2, 0, 0, 1,
      4, 0, 0, 1,
      6, 0, 0, 1,
      4, 0, 0, 1,
      1, 0, 0, 1,
      4, 3, 0, 1,
      3, 3, 0, 1,
      5, 3, 0, 1,
      4, 3, 0, 1,
      1, 3, 0, 1,
      1, 0, 0, 1,
      4, 2, 0, 1,
      5, 2, 0, 1,
      4, 2, 0, 1,
      1, 2, 0, 1,
      4, 0, 0, 4,
      3, 0, 0, 4,
      4, 0, 0, 4,
      1, 0, 0, 4,
      3, 4, 0, 4,
      4, 4, 0, 1,
      1, 4, 0, 1]
    
    not_spin_construct_2: [
      2, 0, 1, 1,
      4, 0, 0, 1,
      6, 0, 0, 1,
      4, 0, 0, 1,
      5, 0, 0, 1,
      4, 0, 0, 1,
      3, 0, 0, 1,
      4, 0, 0, 1,
      1, 0, 0, 1,
      3, 2, 0, 1,
      5, 2, 0, 1,
      3, 2, 0, 1,
      1, 2, 0, 1]
    
    not_spin_construct_3: [
      1, 3, 1, 0,
      4, 0, 1, 1,
      6, 0, 1, 1,
      4, 0, 1, 1,
      2, 0, 1, 1,
      4, 0, 0, 1,
      6, 0, 0, 1,
      4, 0, 0, 1,
      5, 0, 0, 1,
      4, 0, 0, 1,
      3, 0, 0, 1,
      4, 0, 0, 1,
      1, 0, 0, 1,
      3, 2, 0, 1,
      5, 2, 0, 1,
      3, 2, 0, 1,
      1, 2, 0, 1,
      4, 0, 0, 4,
      3, 0, 0, 4,
      4, 0, 0, 4,
      1, 0, 0, 4,
      3, 4, 0, 1,
      4, 4, 0, 1,
      3, 4, 0, 1,
      1, 4, 0, 1]